library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name='books'
urlpatterns = [
    path('',views.home,name="home"),
    path('addbooks',views.addbooks,name="addbooks"),
    path('viewbooks',views.viewbooks,name="viewbooks"),
    path('add1',views.add1,name="add1"),
    path('fact',views.fact,name="fact"),
    path('detail/<int:p>', views.detail, name="detail"),
    path('delete/<int:p>', views.delete, name="delete"),
    path('edit/<int:p>', views.edit, name="edit"),
    path('search',views.search,name="search"),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from books import views
from students import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/students/urls.py
from django.contrib import admin
from django.urls import path
from books import views
from students import views
app_name='students'
urlpatterns = [
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

    path('viewstudents',views.viewstudents,name="viewstudents"),


]

library/books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    price=models.IntegerField()
    pdf=models.FileField(upload_to="books/pdf")
    cover=models.ImageField(upload_to="books/cover",null=True,blank=True)
    def __str__(self):
        return self.title

library/students/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class student(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    #def __str__(self):
     #   return self.name



class CustomUser(AbstractUser):
    phone=models.IntegerField(default=0)
    place=models.TextField(default="")
    def __str__(self):
        return self.username

library/books/forms.py
from django import forms
from books.models import Book

class bookform(forms.ModelForm):
    class Meta:
        model=Book
        fields="__all__"

library/books/views.py
from django.db.models import Q
from books.forms import bookform
from django.shortcuts import render
from books.models import Book
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# Create your views here.

def home(request):
    return render(request,'home.html')

@login_required
def addbooks(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        d=request.FILES['d']
        i=request.FILES['i']
        b=Book.objects.create(title=t,author=a,price=p,pdf=d,cover=i)
        b.save()
        return viewbooks(request)


    return render(request,'addbooks.html')


@login_required

def viewbooks(request):
    k=Book.objects.all()
    return render(request,'viewbooks.html',{'b':k})
@login_required

def add1(request):
    if(request.method=="POST"):#after submission
        form=bookform(request.POST)#create form object initialize wuth values inside request.POST
        if form.is_valid():
            form.save()#saves form object in db  model book
            return viewbooks(request)

    form=bookform()
    return render(request,'addbooks1.html',{'form':form})

@login_required

def fact(request):
    if(request.method=="POST"):
        num=int(request.POST['n'])
        f=1
        for i in range(1,num+1):
            f=f*i
        return render(request,'FACT.HTML',{'fact':f})

    return render(request,'FACT.html')

@login_required

def detail(request,p):
    b=Book.objects.get(id=p)
    return render(request,'bookdetail.html',{'b':b})
@login_required

def delete(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return viewbooks(request)
@login_required

def edit(request,p):
    b=Book.objects.get(id=p)

    if(request.method=="POST"):#after submission
        form=bookform(request.POST,request.FILES,instance=b)#create form object initialize wuth values inside request.POST
        if form.is_valid():
            form.save()#saves form object in db  model book
            return viewbooks(request)


    form=bookform(instance=b)
    return render(request,'edit.html',{'form':form})

def search(request):
    b= None
    q= ""
    if (request.method=="POST"):
        q=request.POST['q']
        b=Book.objects.filter(Q(title__icontains=q)| Q(author__icontains=q))
    return render(request,'search.html',{'q':q,'b':b})

library/students/views.py
from django.shortcuts import render,redirect
from students.models import student
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from students.models import CustomUser
from django.http import HttpResponse
# Create your views here.
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        pl=request.POST['pl']
        n=request.POST['n']
        if(p==cp):
           user=CustomUser.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l,place=pl,phone=n)
           user.save()
           return redirect('books:home')
        else:
          return HttpResponse("not same")


    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("Invalid")

    return render(request,'login.html')


@login_required

def user_logout(request):
    logout(request)
    return redirect('students:login')

def viewstudents(request):
    g=student.objects.all()

    return render(request,'viewstudents.html',{'s':g})

library/templates/FACT.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<center>
<form method="POST">
        {% csrf_token %}
        <div class="mb-3">
           <label class="form-label">Number</label>
           <input type="number" class="form-control" name="n" placeholder="enter number"></div>

        <div class="mb-3">
            <input type="submit" class="form-control btn btn-secondary">
        </div>

</form>
    {% if fact %}
    <h4>factorial is  {{fact}}</h4>
    {% endif %}
</center>
{% endblock %}

library/templates/addbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<center>
<h3>Add page</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control" name="t"  placeholder="enter title">
</div>
<div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a"  placeholder="enter author">
</div>

    <div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="text" class="form-control" name="p" placeholder="enter price">
    </div>

        <div class="mb-3">
  <label  class="form-label">document</label>
  <input type="file" class="form-control" name="d">
    </div>


        <div class="mb-3">
  <label  class="form-label">image</label>
  <input type="file" class="form-control" name="i">
    </div>
        <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
    </form></center>
{% endblock %}

library/templates/addbooks1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h2>add1</h2>
<form method="POST">
    {% csrf_token %}
    <table>
{{form.as_table}}</table>
    <input type="submit">
    </form>
{% endblock %}

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/s.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LIBRARY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbooks' %}">ADD</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'books:fact' %}">FACTORIAL</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:viewbooks' %}">VIEW</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'students:viewstudents' %}">VIEW2</a>
        </li>
                                    <li class="nav-item">
          <a class="nav-link" href="{% url 'students:logout' %}">LOGOUT</a>
        </li>


            {% else %}


                <li class="nav-item">
          <a class="nav-link" href="{% url 'students:register' %}">REGISTER</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'students:login' %}">LOGIN</a>
        </li>
          {% endif %}



      </ul>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <form class="d-flex" method="POST" action="{% url 'books:search' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" name="q" placeholder="search" aria-label="search">
            <button class="btn btn-outline-danger" type="submit">search</button>
        </form>


    </div>
  </div>
</nav>

{% block A %}
{% endblock %}

</body>
</html>

library/templates/bookdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<center>
<h2>book detail</h2>
<table class="table table-bordered">
        <tr>
        <th>ID</th>
        <td>{{b.id}}</td>
    </tr>
        <tr>
        <th>COVER</th>
        <td><img src="{{b.cover.url}}" height="100px" width="200px"></td>
    </tr>
    <tr>
        <th>TITLE</th>
        <td>{{b.title}}</td>
    </tr>
        <tr>
        <th>AUTHOR</th>
        <td>{{b.author}}</td>
    </tr>
        <tr>
        <th>PRICE</th>
        <td>{{b.price}}</td>
    </tr>
        <tr>
        <th>DOCUMENT</th>
        <td><a href="{{b.pdf.url}}">download</a></td>
    </tr>
</table>
    </center>
{{b}}
{% endblock %}

library/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
{{form.as_table}}</table>
    <input type="submit">
    </form>
{% endblock%}

library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h2>home page</h2>
{% if user.is_authenticated %}
{{user.username}}
{% else %}
Guest
{% endif %}
{% endblock%}

library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h2>Login page</h2>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u"  placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter password">
</div>
            <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
</form>
{% endblock %}

library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}<center>
<h2>Register page</h2>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u"  placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter password">
</div>

    <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter password">
    </div>

        <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control" name="e">
    </div>


        <div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f">
    </div>

            <div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l">
    </div>


                <div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="text" class="form-control" name="n">
    </div>

                <div class="mb-3">
  <label  class="form-label">Place</label>
  <input type="text" class="form-control" name="pl">
    </div>

        <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
    </form></center>


{% endblock %}

library/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h1>search page</h1>
{% if b %}

<table class="table table-bordered">
    <tr><th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
    </tr>

    {% for i in b %}
    <tr><td>{{i.id}}</td>
        <td><img src="{{i.cover.url}}" height="100px" width="200px"> </td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><a href="{{i.pdf.url}}">download</a></td>
        <td><a href="{% url 'books:detail' i.id  %}" class="btn btn-secondary">view</a></td>
        <td><a href="{% url 'books:edit' i.id  %}" class="btn btn-light">edit</a></td>
        <td><a href="{% url 'books:delete' i.id  %}" class="btn btn-danger">delete</a></td>




    </tr>
    {% endfor %}
</table>
{% else %}
<b><p>no results</p></b>
{% endif %}


{% endblock%}

library/templates/viewbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h2>View page</h2>

<table class="table table-bordered">
    <tr><th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
    </tr>

    {% for i in b %}
    <tr><td>{{i.id}}</td>
        <td><img src="{{i.cover.url}}" height="100px" width="200px"> </td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><a href="{{i.pdf.url}}">download</a></td>
        <td><a href="{% url 'books:detail' i.id  %}" class="btn btn-secondary">view</a></td>
        <td><a href="{% url 'books:edit' i.id  %}" class="btn btn-light">edit</a></td>
        <td><a href="{% url 'books:delete' i.id  %}" class="btn btn-danger">delete</a></td>




    </tr>
    {% endfor %}
</table>

<ol>
    {% for i in b %}
    <li>Book Details</li>
    <li>{{i.title}}</li>
        <li>{{i.author}}</li>
        <li>{{i.price}}</li>

    {% endfor %}


</ol>

{% endblock %}

library/templates/viewstudents.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block A %}
<h2>view page</h2>

<ol>
    {% for i in s %}
    <li>student details</li>
    <li>{{i.name}}</li>
    <li>{{i.age}}</li>
    {% endfor%}

</ol>

{% endblock %}